### PR TITLE
Feat/add additional e2e tests

### PR DESCRIPTION
**Pull request by tmilost**

### CODE REVIEW

**Comment by RadovanTomik** [comment]
if the CI doesn't pass then this PR needs some more work no?

**Comment by tmilost** [comment]
@RadovanTomik no

**Comment by tmilost** [comment]
@RadovanTomik there is some problem with connecting to backend `[vite] http proxy error at /api/actuator/info:
Error: connect ECONNREFUSED ::1:8081
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)`

**Review by RadovanTomik — CHANGES_REQUESTED** [review]
please maybe change the CI.yml file so that it checks out the latest backend repo uses a docker compose file from one of the tests there? this way the compose file wont get out of date. Plus we should use prod not dev profile for tests as here: [compose.yaml](https://github.com/BBMRI-ERIC/negotiator/blob/master/.github/oauth-test/compose.yaml)

**Review by RadovanTomik — APPROVED** [review]

**Pull request merged**
